version: "3"
services:
  discord-bot-private:
    image: getkarma/discord-bot-nuker:latest
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./data:/app/data
